export const Images = {
  logo: require("./logo.svg"),
  background: require("./bg_image.png"),
  chevron_left: require("./chevron-left.svg"),
  chevron_right: require("./chevron-right.svg"),
  arrow_s_down: require("./arrow-square-down.svg"),
  logofull: require("./logofull.svg").default,
  logosquare: require("./logo-square.png"),
  logowhite: require("./logo-white.svg").default,
  chevronRight: require("./chevron-right.png"),
  chevronDown: require("./chevron-down.png"),

  OGIndex: {
    OGIndex: require("./OGIndex.png"),
    OGIndexApp: require("./OGIndexApp.png"),
    OGIndexXCS: require("./OGIndexXCS.png"),
    OGIndexSeed: require("./OGIndexSeed.png"),
    OGIndexPrometheus: require("./OGIndexPrometheus.png"),
    OGIndexFAQ: require("./OGIndexFAQ.png"),
  },

  graph: require("./graph.png"),

  partners: {
    partner01: require("./partners/swissborg.png"),
    partner02: require("./partners/polygon.png"),
    partner03: require("./partners/brave.png"),
    partner04: require("./partners/ygg.png"),
    partner05: require("./partners/community.png"),
    partner06: require("./partners/ultra.png"),
    partner07: require("./partners/myria.png"),
    partner08: require("./partners/zilliqa.png"),
    partner09: require("./partners/polkastarter.png"),
    partner10: require("./partners/duo.png"),
    swissborg: require("./partners/swissborgicon.png"),

    cryptoslate: require("./partners/cryptoslate.png"),
    esb: require("./partners/esb.png"),
    esi: require("./partners/esi.png"),
  },
  portfolio: {
    harvest: require("./portfolio/harvest.png"),
    rooniverse: require("./portfolio/rooniverse.png"),
    bornless: require("./portfolio/bornless.png"),
    aether: require("./portfolio/aether.png"),
    exverse: require("./portfolio/exverse.png"),
  },
  arrowRight: require("./arrow-right.svg"),
  noimg: require("./noimg.png"),

  // Pages
  aboutUs: {
    mouse: require("./aboutus/mouse.png"),
    keyboard: require("./aboutus/keyboard.png"),
    headset: require("./aboutus/headphone.png"),
    megaphone: require("./aboutus/megaphone.png"),
    confetti: require("./aboutus/confetti.png"),
    crown: require("./aboutus/crown.png"),
    trophy: require("./aboutus/trophy.png"),

    logo02: require("./aboutus/logo.png"),
    smoke1_01: require("./aboutus/smoke_1.png"),
    smoke1_02: require("./aboutus/smoke_2.png"),
    sparks: require("./aboutus/sparks.png"),
    render3d: require("./aboutus/render3d.png"),

    render3d_01: require("./aboutus/render_3d_2.png"),
    smoke01: require("./aboutus/smoke_2_1.png"),
    smoke02: require("./aboutus/smoke_2_2.png"),
    logo01: require("./aboutus/logo2.png"),
    sparks01: require("./aboutus/sparks_02.png"),

    layer1: require("./aboutus/protocol-layer-1.png"),
    layer2: require("./aboutus/protocol-layer-2.png"),
    layer3: require("./aboutus/protocol-layer-3.png"),
    layer4: require("./aboutus/protocol-layer-4.png"),
    layer5: require("./aboutus/protocol-layer-5.png"),
    token: require("./aboutus/token.png"),
    deck: require("./aboutus/deck.png"),

    team: {
      member01: require("./team/louis.png"),
      member02: require("./team/anthony.png"),
      member03: require("./team/laureline.png"),
      member04: require("./team/arthur.png"),
      member05: require("./team/donatas.png"),
      member06: require("./team/gauthier.png"),
      member07: require("./team/paulius.png"),
      member09: require("./team/julienas.png"),
      member10: require("./team/connor.png"),
      member11: require("./team/sam.png"),
      member12: require("./team/joao.png"),
      member13: require("./team/hakim.png"),
      member14: require("./team/sean.png"),
    },
    players: {
      lex: require("./players/lex.png"),
      bicboi: require("./players/bicboi.png"),
      xen0: require("./players/xen0.png"),
      m2rk: require("./players/m2rk.png"),
      eskezje: require("./players/eskezje.png"),
      sjud: require("./players/sjud.png"),
    },
    gcl: require("./xborgapp/gcl.png"),
  },

  XCS: {
    banner: require("./XCS/banner.png"),
    banner_logo: require("./XCS/banner_logo.png"),
    sasakki: require("./XCS/355_Sassaki.png"),
    shado: require("./XCS/356_Shado.png"),
    robo: require("./XCS/boto3.png"),
    red_warrior: require("./XCS/red_warrior.png"),
    erika: require("./XCS/erika.png"),
    camera: require("./XCS/camera.png"),
    production: require("./XCS/production.png"),
    banner2: require("./XCS/banner-2.png"),
    banner2logo: require("./XCS/banner-2-logo.png"),
    banner_twitter: require("./XCS/banner-tw.png"),
    banner_twitch: require("./XCS/banner-twc.png"),
    banner_discord: require("./XCS/banner-dc.png"),

    swissborg: require("./XCS/swissborg.png"),
    brave: require("./XCS/brave.png"),
    communitygaming: require("./XCS/communitygaming.png"),
    gala: require("./XCS/gala.png"),

    evio: require("./XCS/evio.png"),
    godsunchained: require("./XCS/godsunchained.png"),
    mojomelee: require("./XCS/mojomelee.png"),
    cta: require("./XCS/cta.png"),
    bornless: require("./XCS/bornless.png"),
  },

  xborgapp: {
    mage: require("./xborgapp/mage.png"),
    dark_swordsman: require("./xborgapp/dark-swordsman.png"),
    sparkles: require("./xborgapp/sparkles.png"),
    aliens: require("./xborgapp/aliens.png"),
    counter_terrorist: require("./xborgapp/counter-terrorist.png"),
    blue_pet: require("./xborgapp/blue-pet.png"),
    ghostartifact: require("./xborgapp/ghostartifact.png"),
    ghost: require("./xborgapp/ghost.png"),

    folder: require("./launchpad/folder.png"),
    deck: require("./launchpad/deck.png"),
    row1: require("./launchpad/leaderboard1.png"),
    row2: require("./launchpad/leaderboard2.png"),
    row3: require("./launchpad/leaderboard3.png"),

    ugp1: require("./xborgapp/ugp1.png"),
    ugp2: require("./xborgapp/ugp2.png"),
    ugp3: require("./xborgapp/ugp3.png"),
    ugp4: require("./xborgapp/ugp4.png"),
    ugp5: require("./xborgapp/ugp5.png"),
    ugp6: require("./xborgapp/ugp6.png"),
    ugp7: require("./xborgapp/ugp7.png"),
    ugp8: require("./xborgapp/ugp8.png"),
    ugp9: require("./xborgapp/ugp9.png"),
    ugp1avatar: require("./xborgapp/ugp1avatar.png"),
    ugp2avatar: require("./xborgapp/ugp2avatar.png"),
    ugp3avatar: require("./xborgapp/ugp3avatar.png"),
    ugp4avatar: require("./xborgapp/ugp4avatar.png"),
    ugp5avatar: require("./xborgapp/ugp5avatar.png"),
    ugp6avatar: require("./xborgapp/ugp6avatar.png"),
    ugp7avatar: require("./xborgapp/ugp7avatar.png"),
    ugp8avatar: require("./xborgapp/ugp8avatar.png"),
    ugp9avatar: require("./xborgapp/ugp9avatar.png"),

    badge: require("./xborgapp/badge.png"),
    lights: require("./xborgapp/lights.png"),

    orb: require("./xborgapp/orb.png"),
    promo: require("./xborgapp/promo.png"),
    game: require("./xborgapp/game.svg").default,

    collectible1: require("./xborgapp/collectible1.png"),
    collectible2: require("./xborgapp/collectible2.png"),
    hair1: require("./xborgapp/hair1.png"),
    artifact: require("./xborgapp/artifact.png"),
  },

  invest: {
    teambds: require("./invest/teambds.png"),

    graph: require("./invest/graph.svg").default,
    medal: require("./invest/medal.svg").default,
    coins: require("./invest/coins.svg").default,

    chart1: require("./invest/chart1.png"),
    chart2: require("./invest/chart2.png"),
    chart3: require("./invest/chart3.png"),
    chart4: require("./invest/chart4.png"),
    chart5: require("./invest/chart5.png"),
    chart6: require("./invest/chart6.png"),
    chart7: require("./invest/chart7.png"),

    swissborg: require("./invest/swissborg.png"),

    swiss1: require("./invest/swiss1.png"),
    swiss2: require("./invest/swiss2.png"),
    swiss3: require("./invest/swiss3.png"),
    swiss4: require("./invest/swiss4.png"),

    prometheus: require("./invest/prometheus.png"),

    thalon: require("./invest/thalon.png"),
    exverse: require("./invest/exverse.png"),
    aether: require("./invest/aether.png"),
    bornless: require("./invest/bornless.png"),
    harvest: require("./invest/harvest.png"),
    rooniverse: require("./invest/rooniverse.png"),

    xborgapp_1: require("./invest/xborgapp-1.png"),
    xborgapp_2: require("./invest/xborgapp-2.png"),
    xborgapp_3: require("./invest/xborgapp-3.png"),
  },

  news: {
    xborgbds: require("./news/xborgxbds.png"),
    revolution: require("./news/revolution.png"),
    cyberlink4: require("./news/cyberlink4.png"),
    cyberlink5: require("./news/cyberlink5.png"),
    cyberlink6: require("./news/cyberlink6.png"),
    cyberlinkqa: require("./news/cyberlinkqa.png"),
    twitterama: require("./news/twitterama.png"),
    seed: require("./news/seed.png"),
  },
};
