export const Images = {
  logo: require("./logo.svg"),
  background: require("./bg_image.png"),
  chevron_left: require("./chevron-left.svg"),
  chevron_right: require("./chevron-right.svg"),
  arrow_s_down: require("./arrow-square-down.svg"),
  logofull: require("./logofull.svg").default,
  partners: {
    partner01: require("./partners/swissborg.png"),
    partner02: require("./partners/myria.png"),
    partner03: require("./partners/ultra.png"),
    partner04: require("./partners/communitygaming.png"),
    partner05: require("./partners/blackpool.png"),
    partner06: require("./partners/zilliqa.png"),
    partner07: require("./partners/polkastarter.png"),
  },
  portfolio: {
    harvest: require("./portfolio/harvest.png"),
    rooniverse: require("./portfolio/rooniverse.png"),
    bornless: require("./portfolio/bornless.png"),
    aether: require("./portfolio/aether.png"),
    exverse: require("./portfolio/exverse.png"),
  },
  arrowRight: require("./arrow-right.svg"),
  noimg: require("./noimg.png"),

  // Pages
  aboutUs: {
    mouse: require("./aboutus/mouse.png"),
    keyboard: require("./aboutus/keyboard.png"),
    headset: require("./aboutus/headphone.png"),
    megaphone: require("./aboutus/megaphone.png"),
    confetti: require("./aboutus/confetti.png"),
    crown: require("./aboutus/crown.png"),
    trophy: require("./aboutus/trophy.png"),

    logo02: require("./aboutus/logo.png"),
    smoke1_01: require("./aboutus/smoke_1.png"),
    smoke1_02: require("./aboutus/smoke_2.png"),
    sparks: require("./aboutus/sparks.png"),
    render3d: require("./aboutus/render3d.png"),

    render3d_01: require("./aboutus/render_3d_2.png"),
    smoke01: require("./aboutus/smoke_2_1.png"),
    smoke02: require("./aboutus/smoke_2_2.png"),
    logo01: require("./aboutus/logo2.png"),
    sparks01: require("./aboutus/sparks_02.png"),
    team: {
      member01: require("./team/louis.png"),
      member02: require("./team/connor.png"),
      member03: require("./team/joao.png"),
      member04: require("./team/hakim.png"),
      member05: require("./team/paulius.png"),
      member06: require("./team/gauthier.png"),
      member07: require("./team/sam.png"),
      member08: require("./team/travis.png"),
      member09: require("./team/julienas.png"),
      member10: require("./team/sean.png"),
    },
    players: {
      lex: require("./players/lex.png"),
      bicboi: require("./players/bicboi.png"),
      xen0: require("./players/xen0.png"),
      m2rk: require("./players/m2rk.png"),
      eskezje: require("./players/eskezje.png"),
      sjud: require("./players/sjud.png"),
    },
  },

  esports: {
    trophy: require("./esports/trophy.png"),
    controller: require("./esports/controller.png"),
    coin1: require("./esports/coin1.png"),
    coin2: require("./esports/coin2.png"),
    coin3: require("./esports/coin3.png"),
    rectangle: require("./esports/rectangle.png"),
    rectangle2: require("./esports/rectangle2.png"),
    rectangle3: require("./esports/rectangle3.png"),
    eth: require("./esports/ethcoin.png"),
    eth_blocks: require("./esports/ethcoin_blocks.png"),
    phone: require("./esports/phone.png"),
    tshirt1: require("./esports/tshirt1.png"),
    tshirt1_design: require("./esports/tshirt1_design.png"),
    tshirt1_number: require("./esports/tshirt1_number.png"),
    tshirt2: require("./esports/tshirt2.png"),
    tshirt2_design: require("./esports/tshirt2_design.png"),
    tshirt2_number: require("./esports/tshirt2_number.png"),
    flames: require("./esports/flames.png"),
    sparkles: require("./esports/sparkles.png"),
  },

  XCS: {
    banner: require("./XCS/banner.png"),
    banner_logo: require("./XCS/banner_logo.png"),
    sasakki: require("./XCS/355_Sassaki.png"),
    shado: require("./XCS/356_Shado.png"),
    robo: require("./XCS/boto3.png"),
    red_warrior: require("./XCS/red_warrior.png"),
    erika: require("./XCS/erika.png"),
    camera: require("./XCS/camera.png"),
    movie: require("./XCS/movie.png"),
    production: require("./XCS/production.png"),
    banner2: require("./XCS/banner-2.png"),
    banner2logo: require("./XCS/banner-2-logo.png"),
    banner_twitter: require("./XCS/banner-tw.png"),
    banner_twitch: require("./XCS/banner-twc.png"),
    banner_discord: require("./XCS/banner-dc.png"),

    swissborg: require("./XCS/swissborg.png"),
    brave: require("./XCS/brave.png"),
    communitygaming: require("./XCS/communitygaming.png"),
    gala: require("./XCS/gala.png"),

    evio: require("./XCS/evio.png"),
    harvest: require("./XCS/theharvest.png"),
    godsunchained: require("./XCS/godsunchained.png"),
    hidden04: require("./XCS/hidden04.png"),
    hidden05: require("./XCS/hidden05.png"),
  },

  gamingpassport: {
    profile_bg: require("./gamingpassport/profile-bg.png"),
    gaming_profile: require("./gamingpassport/gaming-profile.png"),
    scout: require("./gamingpassport/scout.png"),
    steam: require("./gamingpassport/steam.png"),
    plugnplay: require("./gamingpassport/plugnplay.png"),
    epic: require("./gamingpassport/epic.png"),
    karambit: require("./gamingpassport/karambit.png"),
    swordsman: require("./gamingpassport/swordsman.png"),
    ethcoin: require("./gamingpassport/ethcoin.png"),
    gun: require("./gamingpassport/gun.png"),
    emerald: require("./gamingpassport/emerald.png"),
    mage: require("./gamingpassport/mage.png"),
    dark_swordsman: require("./gamingpassport/dark-swordsman.png"),
    sparkles: require("./gamingpassport/sparkles.png"),
    aliens: require("./gamingpassport/aliens.png"),
    counter_terrorist: require("./gamingpassport/counter-terrorist.png"),
    blue_pet: require("./gamingpassport/blue-pet.png"),
    artifact: require("./gamingpassport/artifact.png"),
    ghost: require("./gamingpassport/ghost.png"),
  },

  launchpad: {
    bowman: require("./launchpad/bowman.png"),
    terrorist: require("./launchpad/terrorist.png"),
    tft_penguin: require("./launchpad/tft_penguin.png"),
    folder: require("./launchpad/folder.png"),
    bolt: require("./launchpad/bolt.png"),
    flask: require("./launchpad/flask.png"),
    hanzo: require("./launchpad/hanzo.png"),
    giaco: require("./launchpad/giaco.png"),
    robot: require("./launchpad/robot.png"),
    row1: require("./launchpad/leaderboard1.png"),
    row2: require("./launchpad/leaderboard2.png"),
    row3: require("./launchpad/leaderboard3.png"),
  },
};
